import { afterEach, expect, it, vi } from "vitest";
import { NotificationQueue, PauseSuggestions } from "./notifications";
afterEach(() => vi.useRealTimers());
it("presents queued feedback in order and clears timers when replaced or disposed", async () => {
  vi.useFakeTimers();
  const show = vi.fn();
  const queue = new NotificationQueue(show);
  queue.push("first", 1000);
  queue.push("second", 1000);
  expect(show.mock.calls).toEqual([["first"]]);
  await vi.advanceTimersByTimeAsync(1000);
  expect(show).toHaveBeenLastCalledWith("second");
  queue.clear();
  await vi.advanceTimersByTimeAsync(2000);
  expect(show).toHaveBeenLastCalledWith("");
  queue.push("indefinite");
  queue.push("waiting", 10);
  await vi.advanceTimersByTimeAsync(2000);
  expect(show).toHaveBeenLastCalledWith("indefinite");
  queue.clear();
});
it("suggests a sentence after four seconds and paragraph after seven, canceling both on renewed speech", async () => {
  vi.useFakeTimers();
  const show = vi.fn();
  const suggestions = new PauseSuggestions(show);
  suggestions.heard();
  await vi.advanceTimersByTimeAsync(3999);
  expect(show).not.toHaveBeenCalled();
  await vi.advanceTimersByTimeAsync(1);
  expect(show).toHaveBeenLastCalledWith("sentence");
  await vi.advanceTimersByTimeAsync(3000);
  expect(show).toHaveBeenLastCalledWith("paragraph");
  suggestions.heard();
  await vi.advanceTimersByTimeAsync(3000);
  suggestions.heard();
  await vi.advanceTimersByTimeAsync(3000);
  expect(show).toHaveBeenCalledTimes(2);
  suggestions.stop();
  await vi.advanceTimersByTimeAsync(10000);
  expect(show).toHaveBeenCalledTimes(2);
});
