"""Extract native command identities and grammar to make web coverage track the Swift source."""
import json
import re
from pathlib import Path

root = Path(__file__).resolve().parent.parent
source = (root / 'diction-processor/VoiceCommandEngine.swift').read_text()
clean = re.sub(r'//[^\n]*', '', source)
commands_section = clean.split('public enum VoiceCommand:')[1].split('func value()')[0]
commands = re.findall(r'case (\w+) = "([^"]+)"', commands_section)
tokens_section = clean.split('public enum Token:')[1].split('func value()')[0]
tokens = dict(re.findall(r'case (\w+) = "([^"]+)"', tokens_section))
alias_section = clean.split('let TokenMap:')[1].split('let VoiceCommandMap:')[0]
aliases = {tokens[name]: target for name, target in re.findall(r'Token\.(\w+)\.value\(\)\s*:\s*\.(\w+)', alias_section)}
aliases.update(dict(re.findall(r'"([^"]+)"\s*:\s*\.(\w+)', alias_section)))
map_section = clean.split('let VoiceCommandMap:')[1].split('let ActionToken:')[0]
grammar = [{'tokens': re.findall(r'\.(\w+)', raw), 'command': command} for raw, command in re.findall(r'Set\(\[([^\]]+)\]\)\s*:\s*\.(\w+)', map_section)]
header = '// ** IMPORTANT **: Keep in sync with diction-processor/VoiceCommandEngine.swift.\n// Generated by scripts/extract-command-catalog.py from the Swift command catalog.\n'
(root / 'web/src/enums/command.ts').write_text(header + 'export enum Command {\n' + ''.join(f'  {key} = "{key}",\n' for key, _ in commands) + '}\n')
(root / 'web/src/lib/native-commands.json').write_text(json.dumps({'commands': [{'id': key, 'label': value} for key, value in commands], 'aliases': aliases, 'grammar': grammar}, indent=2) + '\n')
print(f'{len(commands)} native commands, {len(aliases)} aliases, {len(grammar)} grammar rules')
